### ISSUE TITLE
When slide to the next video，the current device can't control

### ISSUE THREAD

**Issue by ZengZeHong** [CharonChui/CyberLink4Android#7]
I found that if you slide to the next video，the current device can't control.But if you slide back to the original position,it can control again。

**Comment by CharonChui** [comment]
Have you switch url to the next video ?

**Comment by ZengZeHong** [comment]
Of course!  I tested it in your demo。When slide to the next video，it can play normally，but can't control。When I paused and restarted ， it can control again。The moment it can't control is occurred that you slide to the next video。Besides，it may be the device problems。
